### ISSUE TITLE
CI/CD ? Travis or something else?

### ISSUE THREAD

**Issue by paulywill** [chingu-voyages/v9-bears-team-11#6]
@shimphillip, I'm only familiar with Travis CI.

Do you want to use something like that or try something else?

Circle CI?

**Comment by ghost** [comment]
Let's go with Travis. I actually never used before, you can teach me!

**Comment by paulywill** [comment]
It starts with getting one of the facilitators to grant us access.

![image](https://user-images.githubusercontent.com/602422/59148349-c94fcb80-89d5-11e9-9264-add70dca6605.png)


Then we create a YAML for Travis (.travis.yml) in our home directory.

Something like (but not exactly):

```
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
after_success:
  - "npm run deploy"
```
